### ISSUE TITLE
Deleting a Vocabulary with Tags raises and error

### ISSUE THREAD

**Issue by osahon-okungbowa** [datopian/ckanext-vocabulary#7]
Deleting a vocabulary that still contains tags throws a server error (See screenshot).

- It would be good to delete all existing tags from a Vocabulary **before** deleting the Vocabulary.

- Also, display a pop confirmation message to the user informing them that all tags will be deleted from this Vaocabualry in addition to deleting the Vocabulary. 

![image](https://user-images.githubusercontent.com/60897650/156122266-be018d85-c7fa-41d0-8a89-a7530bbb9a66.png)

**Comment by MuhammadIsmailShahzad** [comment]
Error traceback:
```
```
